# ===============================
# Server Configuration
# ===============================
# Spring Boot 서버 포트
server.port=8080

# ===============================
# CORS Configuration
# ===============================
# React 개발 서버(3000) 허용
spring.web.cors.allowed-origins=http://localhost:3000 
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allow-credentials=true

# ===============================
# MongoDB Configuration
# ===============================
# 로컬 MongoDB 접속 예시
spring.data.mongodb.uri=mongodb://localhost:27017/farmDB

#파일 업로드를 위한 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.location=C:/vscode/pro/farm/backend/uploads/tmp/

# ===============================
# Logging
# ===============================
# 콘솔 로그 출력
logging.level.org.springframework=INFO

spring.data.mongodb.database=farmDB

# 카카오
kakao.client-id=96a4a7dfe35ee2e71a6d030c21bfacec
kakao.redirect-uri=http://localhost:3000/oauth/kakao

spring.data.mongodb.auto-index-creation=true

solapi.api-key=NCSWUPBMNEA7HAJA
solapi.api-secret=RW19EWASASX5IBNHTYZRNGZ88EVUKTF0
solapi.from-number=01075130638


